/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulatheure;

import Reseau.*;
import java.util.List;
import java.io.*;
import java.awt.*;
import java.awt.image.*;
import javax.imageio.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author rem54
 */
public class SimulatHeure extends javax.swing.JFrame {

    /**
     * Creates new form SimulatHeure
     */
    public Simulation Sim;
    public Node selectedNode;
    public Node bufferedNode;
    public Route selectedRoute;
    public Point pointBuffer;
    public int lineCreationState;
    public String selectedObjectType;
    public String createRouteState;
    public SimTimer simTimer;
    
    
    public DefaultListModel defaultListModel;
    
    public SimulatHeure() {
        
        initComponents();
        Sim = fenetre_sim1.Sim;
        createRouteState = "Demande param";
        defaultListModel = new DefaultListModel();
        liste_circuits.setModel(defaultListModel);
        Dialog_circuit.pack();
        lineCreationState =0;
        simTimer = new SimTimer(Sim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Dialog_circuit = new javax.swing.JDialog();
        ok_dialog_circuit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spin_num = new javax.swing.JSpinner();
        spin_freq = new javax.swing.JSpinner();
        spin_t = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem12 = new javax.swing.JMenuItem();
        Radio_ajouter = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Print = new javax.swing.JTextPane();
        Radio_select = new javax.swing.JRadioButton();
        fenetre_sim1 = new simulatheure.SimDisplay();
        Radio_deplacer = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        text_nom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        liste_circuits = new javax.swing.JList();
        Bouton_circuit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Radio_arete = new javax.swing.JRadioButton();
        Radio_noeud = new javax.swing.JRadioButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        Bouton_arreter = new javax.swing.JButton();
        Bouton_simuler = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        sim_duration = new javax.swing.JTextField();
        simulation_speed = new javax.swing.JSlider();
        Bouton_supprimer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFolderFichier = new javax.swing.JMenu();
        menuCommandNouvDoc = new javax.swing.JMenuItem();
        menuCommandOuvrir = new javax.swing.JMenuItem();
        menuCommandEnregistrer = new javax.swing.JMenuItem();
        menuCommandEnregSous = new javax.swing.JMenuItem();
        menuFolderEdition = new javax.swing.JMenu();
        menuCommandAjouterNoeud = new javax.swing.JMenuItem();
        menuCommandAjouterStation = new javax.swing.JMenuItem();
        menuFolderSimulation = new javax.swing.JMenu();
        menuCommandLancerSim = new javax.swing.JMenuItem();
        menuCommandStopperSim = new javax.swing.JMenuItem();
        menuCommandAnalResults = new javax.swing.JMenuItem();
        menuFolderCircuit = new javax.swing.JMenu();
        menuCommandAjouterCircuit = new javax.swing.JMenuItem();
        menuCommandModCircuit = new javax.swing.JMenuItem();
        menuFolderAffichage = new javax.swing.JMenu();
        menuSubfolderToolboxes = new javax.swing.JMenu();
        menuOptionSeeCircuitToolbox = new javax.swing.JCheckBoxMenuItem();
        menuOptionSeeSimToolbox = new javax.swing.JCheckBoxMenuItem();
        menuSubfolderInformation = new javax.swing.JMenu();
        menuOptionSeeCoordsDisplay = new javax.swing.JCheckBoxMenuItem();
        menuOptionSeeTooltipsDisplay = new javax.swing.JCheckBoxMenuItem();

        Dialog_circuit.setAlwaysOnTop(true);
        Dialog_circuit.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        Dialog_circuit.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        Dialog_circuit.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                Dialog_circuitWindowClosing(evt);
            }
        });

        ok_dialog_circuit.setText("Ok");
        ok_dialog_circuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_dialog_circuitActionPerformed(evt);
            }
        });

        jLabel3.setText("Numéro");

        jLabel4.setText("Fréquence");

        jLabel5.setText("Temps avant premier départ");

        spin_num.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        spin_freq.setModel(new javax.swing.SpinnerNumberModel(5, 0, 999, 1));

        spin_t.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        javax.swing.GroupLayout Dialog_circuitLayout = new javax.swing.GroupLayout(Dialog_circuit.getContentPane());
        Dialog_circuit.getContentPane().setLayout(Dialog_circuitLayout);
        Dialog_circuitLayout.setHorizontalGroup(
            Dialog_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_circuitLayout.createSequentialGroup()
                .addGroup(Dialog_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dialog_circuitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Dialog_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(Dialog_circuitLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ok_dialog_circuit))
                    .addGroup(Dialog_circuitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_circuitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spin_freq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Dialog_circuitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spin_t, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dialog_circuitLayout.setVerticalGroup(
            Dialog_circuitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_circuitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spin_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spin_freq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spin_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ok_dialog_circuit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SimulatHeure");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(762, 520));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        buttonGroup1.add(Radio_ajouter);
        Radio_ajouter.setText("Ajouter Station");
        Radio_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_ajouterActionPerformed(evt);
            }
        });

        Print.setEditable(false);
        Print.setBorder(null);
        Print.setToolTipText("");
        Print.setFocusable(false);
        jScrollPane1.setViewportView(Print);

        buttonGroup1.add(Radio_select);
        Radio_select.setText("Selectionner");
        Radio_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_selectActionPerformed(evt);
            }
        });

        fenetre_sim1.setBackground(new java.awt.Color(255, 255, 255));
        fenetre_sim1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fenetre_sim1.setAutoscrolls(true);
        fenetre_sim1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fenetre_sim1MouseMoved(evt);
            }
        });
        fenetre_sim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fenetre_sim1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout fenetre_sim1Layout = new javax.swing.GroupLayout(fenetre_sim1);
        fenetre_sim1.setLayout(fenetre_sim1Layout);
        fenetre_sim1Layout.setHorizontalGroup(
            fenetre_sim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        fenetre_sim1Layout.setVerticalGroup(
            fenetre_sim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        buttonGroup1.add(Radio_deplacer);
        Radio_deplacer.setText("Déplacer");
        Radio_deplacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_deplacerActionPerformed(evt);
            }
        });

        jLabel2.setText("Coordonnées");

        jInternalFrame1.setTitle("Circuit");
        jInternalFrame1.setAutoscrolls(true);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jInternalFrame1MouseEntered(evt);
            }
        });

        jLabel1.setText("Nom");

        text_nom.setToolTipText("");
        text_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nomActionPerformed(evt);
            }
        });

        jLabel6.setText("Circuits");

        liste_circuits.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        liste_circuits.setMaximumSize(new java.awt.Dimension(100, 100));
        liste_circuits.setMinimumSize(new java.awt.Dimension(100, 100));
        liste_circuits.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                liste_circuitsFocusGained(evt);
            }
        });
        liste_circuits.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                liste_circuitsValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(liste_circuits);

        Bouton_circuit.setText("Ajouter Circuit");
        Bouton_circuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_circuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_nom)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(Bouton_circuit, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bouton_circuit)
                .addContainerGap())
        );

        buttonGroup1.add(Radio_arete);
        Radio_arete.setText("Arete");
        Radio_arete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_areteActionPerformed(evt);
            }
        });

        buttonGroup1.add(Radio_noeud);
        Radio_noeud.setText("Noeud");
        Radio_noeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_noeudActionPerformed(evt);
            }
        });

        jInternalFrame2.setTitle("Simulation");
        jInternalFrame2.setVisible(true);

        Bouton_arreter.setText("Arrêter");
        Bouton_arreter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_arreterActionPerformed(evt);
            }
        });

        Bouton_simuler.setText("Simuler");
        Bouton_simuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_simulerActionPerformed(evt);
            }
        });

        jLabel7.setText("Durée");

        sim_duration.setText("60");
        sim_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sim_durationActionPerformed(evt);
            }
        });

        simulation_speed.setMinimum(1);
        simulation_speed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                simulation_speedStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sim_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bouton_arreter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Bouton_simuler))
                    .addComponent(simulation_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bouton_arreter)
                    .addComponent(Bouton_simuler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulation_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sim_duration, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        Bouton_supprimer.setText("Supprimer");
        Bouton_supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Bouton_supprimerMouseReleased(evt);
            }
        });

        menuFolderFichier.setText("Fichier");

        menuCommandNouvDoc.setText("Nouveau document");
        menuFolderFichier.add(menuCommandNouvDoc);

        menuCommandOuvrir.setText("Ouvrir");
        menuFolderFichier.add(menuCommandOuvrir);

        menuCommandEnregistrer.setText("Enregistrer");
        menuFolderFichier.add(menuCommandEnregistrer);

        menuCommandEnregSous.setText("Enregistrer sous");
        menuFolderFichier.add(menuCommandEnregSous);

        jMenuBar1.add(menuFolderFichier);

        menuFolderEdition.setText("Edition");

        menuCommandAjouterNoeud.setText("Ajouter Noeud");
        menuCommandAjouterNoeud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCommandAjouterNoeudActionPerformed(evt);
            }
        });
        menuFolderEdition.add(menuCommandAjouterNoeud);

        menuCommandAjouterStation.setText("Ajouter Station");
        menuCommandAjouterStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCommandAjouterStationActionPerformed(evt);
            }
        });
        menuFolderEdition.add(menuCommandAjouterStation);

        jMenuBar1.add(menuFolderEdition);

        menuFolderSimulation.setText("Simulation");

        menuCommandLancerSim.setText("Lancer simulation");
        menuFolderSimulation.add(menuCommandLancerSim);

        menuCommandStopperSim.setText("Stopper simulation");
        menuFolderSimulation.add(menuCommandStopperSim);

        menuCommandAnalResults.setText("Analyser resultats");
        menuFolderSimulation.add(menuCommandAnalResults);

        jMenuBar1.add(menuFolderSimulation);

        menuFolderCircuit.setText("Circuit");

        menuCommandAjouterCircuit.setText("Ajouter");
        menuFolderCircuit.add(menuCommandAjouterCircuit);

        menuCommandModCircuit.setText("Modifier");
        menuFolderCircuit.add(menuCommandModCircuit);

        jMenuBar1.add(menuFolderCircuit);

        menuFolderAffichage.setText("Affichage");

        menuSubfolderToolboxes.setText("Barres d'outils");

        menuOptionSeeCircuitToolbox.setSelected(true);
        menuOptionSeeCircuitToolbox.setText("Circuit");
        menuSubfolderToolboxes.add(menuOptionSeeCircuitToolbox);

        menuOptionSeeSimToolbox.setSelected(true);
        menuOptionSeeSimToolbox.setText("Simulation");
        menuSubfolderToolboxes.add(menuOptionSeeSimToolbox);

        menuFolderAffichage.add(menuSubfolderToolboxes);

        menuSubfolderInformation.setText("Informations");

        menuOptionSeeCoordsDisplay.setSelected(true);
        menuOptionSeeCoordsDisplay.setText("Coordonées");
        menuOptionSeeCoordsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionSeeCoordsDisplayActionPerformed(evt);
            }
        });
        menuSubfolderInformation.add(menuOptionSeeCoordsDisplay);

        menuOptionSeeTooltipsDisplay.setSelected(true);
        menuOptionSeeTooltipsDisplay.setText("Infobulle");
        menuSubfolderInformation.add(menuOptionSeeTooltipsDisplay);

        menuFolderAffichage.add(menuSubfolderInformation);

        jMenuBar1.add(menuFolderAffichage);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Radio_ajouter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Radio_deplacer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Radio_select, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Radio_arete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Radio_noeud, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Bouton_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fenetre_sim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jInternalFrame1)
                            .addComponent(jInternalFrame2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(fenetre_sim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Radio_ajouter)
                        .addComponent(Radio_deplacer)
                        .addComponent(Radio_select)
                        .addComponent(Radio_arete)
                        .addComponent(Radio_noeud))
                    .addComponent(Bouton_supprimer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void createRoute(){
       switch (createRouteState){
           
       //deuxieme clic, crée le circuit
       case "reset": // reset
          createRouteState = "Demande param";
          Radio_ajouter.setEnabled(true);
          Radio_deplacer.setEnabled(true);
          Print.setText("Création de circuit annulée");
          break;
           
       case "Creation":
          if (Sim.newRoute.size()>1){
            
            selectedRoute = Sim.addRoute(Sim.newRoute, (Integer)spin_num.getValue(), (Integer)spin_freq.getValue(), (Integer)spin_t.getValue());
            selectedObjectType = "Circuit";
            
            Sim.newRoute.clear();
            
            defaultListModel.addElement(selectedRoute.getNumber());
            liste_circuits.setSelectedIndex(liste_circuits.getLastVisibleIndex());
            Print.setText("Circuit "+ selectedRoute.getNumber()+ " créé avec succès!");
            fenetre_sim1.repaint();
          }
          else{
              Print.setText("Vous n'avez pas selectionné assez de stations!");
          }
          createRouteState = "Demande param";
          Radio_ajouter.setEnabled(true);
          Radio_deplacer.setEnabled(true);
          break;
       
        //premier clic (mode selection de stations)
       case  "Demande param":
           fenetre_sim1.clearSelection();
           //dialog
           Dialog_circuit.setVisible(true);
           //
           // cas ou on pese sur le X du dialog
           if (createRouteState == "reset"){
               createRoute();
               break;
           }
           
           Radio_ajouter.setEnabled(false);
           Radio_deplacer.setEnabled(false);
           Radio_select.setSelected(true);
           List<Node> circuit = new ArrayList<Node>();
           Print.setText("Veuillez sélectionner la station 1 du circuit.");
           createRouteState = "Creation";
           Sim.newRoute.clear();
           
           break;
       default:
           break;
           
       }
    }
    public void createNode(int x, int y){
        Line aSelect;
           
        aSelect = null;
        if(selectedNode == null){
            aSelect = Sim.isLine(x,y); 
        }
        if(aSelect != null){
            selectedNode = Sim.splitLine(aSelect, x, y);
            selectedObjectType = "Noeud";
            Print.setText("Noeud selectionne!");
            fenetre_sim1.selectNode(selectedNode);
        }
        //Nouveau point
        else if (selectedNode == null){
            selectedNode = Sim.addNode(x, y);
            selectedObjectType = "Noeud";
            Print.setText("Noeud selectionne!");
            fenetre_sim1.selectNode(selectedNode);
        }

    }
    
    
    public void createLine(int x, int y){
        Line aSelect;

        switch (lineCreationState){
            case 0:
                aSelect = null;
                if(selectedNode == null){
                    aSelect = Sim.isLine(x,y); 
                }
                
                if(aSelect != null){
                    bufferedNode = Sim.splitLine(aSelect, x, y);
                }
                //Nouveau point
                else if (selectedNode == null){
                    pointBuffer = new Point(x, y);
                    bufferedNode = null;
                    
                }
                //point existant
                else{
                    bufferedNode = selectedNode;
                    selectedNode = null;
                }
                    
                lineCreationState = 1;
                break;
                
            case 1:
                Node noeud1;
                Node noeud2;
                aSelect = null;
                if (selectedNode == null && bufferedNode == null){
                    noeud1 = new Node(pointBuffer.x,pointBuffer.y);
                     aSelect = null;
                     if(selectedNode == null){
                        aSelect = Sim.isLine(x,y); 
                     }
                    if (aSelect != null){
                        noeud2 = Sim.splitLine(aSelect, x, y);
                    }
                    else{
                        noeud2 = new Node(x,y);
                    }
                }
                
                else if (selectedNode != null && bufferedNode == null){
                    noeud1 = new Node(pointBuffer.x,pointBuffer.y);
                    noeud2 = selectedNode;
                }
                else if (selectedNode == null && bufferedNode != null){
                    noeud1 = bufferedNode;
                    aSelect = null;
                     if(selectedNode == null){
                        aSelect = Sim.isLine(x,y); 
                     }
                
                    if (aSelect != null){
                        noeud2 = Sim.splitLine(aSelect, x, y);
                    }
                    else{
                        noeud2 = new Node(x,y);
                    }
                }
                else{ //(Noeud_selectionne != null && noeudBuffer != null){
                    noeud1 = bufferedNode;
                    noeud2 = selectedNode;
                }
                Sim.addLine(noeud1, noeud2);
                selectedObjectType = "Noeud";
                selectedNode = noeud2;
                lineCreationState = 0;
                fenetre_sim1.selectNode(noeud2);
                break;
            default:
                break;
        }
    }
    
    
    private void Radio_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_ajouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_ajouterActionPerformed

    private void Radio_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_selectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_selectActionPerformed

    private void text_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nomActionPerformed
        // TODO add your handling code here:
         selectedNode.setName(text_nom.getText());
         if (selectedNode.isStation){
            Print.setText("Station selectionnée: " + text_nom.getText());
         }

         
    }//GEN-LAST:event_text_nomActionPerformed

    private void fenetre_sim1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fenetre_sim1MousePressed
        
        
        //coordonnées du clic
        int x = evt.getX();
        int y = evt.getY();
        fenetre_sim1.x = x;
        fenetre_sim1.y = y;
        
        fenetre_sim1.clearSelection();
        /* -------------- Selection d'un Noeud ------------- */
        
        int size = 20;//   
        int size_s = fenetre_sim1.img_station_size; //taille d'une station
        
        if (Radio_select.isSelected() || Radio_arete.isSelected() || Radio_noeud.isSelected()  || Radio_ajouter.isSelected()){
            //va chercher la station correspondant au clic
            selectedNode = Sim.getNodeFromPosition(x,y, size, size_s);
            if (selectedNode == null){
                Print.setText("Vous n'avez rien sélectionné");
                text_nom.setText("-");
            }
            if (selectedNode != null){
                selectedObjectType = "Noeud";
                Print.setText("Noeud selectionne!");
                if (selectedNode.isStation){
                    selectedObjectType = "Station";
                    Print.setText("Station selectionnée: "+selectedNode.getName());
                    text_nom.setText(selectedNode.getName());
                }
            }

            /* -------------- Ajout de station à un circuit ------------- */
            if (createRouteState == "Creation"){
                if (selectedNode != null){
                    Boolean isPossible = false;
                    if (Sim.newRoute.size()>0){
                        for (Line a: Sim.newRoute.get(Sim.newRoute.size()-1).listRoutes){
                            if (selectedNode != Sim.newRoute.get(Sim.newRoute.size()-1)){
                                if (selectedNode == a.origine || selectedNode == a.destination){
                                 isPossible = true;
                                 break;
                                }
                            }
                        }
                    }
                    if (isPossible || Sim.newRoute.isEmpty()){
                        Sim.newRoute.add(selectedNode);
                        Print.setText("Noeud ajoutée (" +selectedNode.getName()+  ") au parcours!");
                        fenetre_sim1.selectNode(selectedNode);
                    }
                    else{
                        Print.setText("Veuillez sélectionner un noeud valide!");
                    }
                }
            }
            else {
                fenetre_sim1.selectNode(selectedNode);
            }
         }
                
            
        /* -------------- Ajout d'une station ------------- */
        
        if (Radio_ajouter.isSelected())
        {
            if (selectedNode != null){
                Sim.addStation(selectedNode);
                selectedObjectType = "Station";
                Print.setText("Derniere station: " + selectedNode.getName());
                text_nom.setText(selectedNode.getName());
                //fenetre_sim1.selectNoeud(Noeud_selectionne);
            }
        }
        
        /* -------------- Deplacer station ------------- */
        
        if (Radio_deplacer.isSelected()){
            if (selectedNode != null)
            {
                selectedNode.setpositionX(x);
                selectedNode.setPositionY(y);
                //fenetre_sim1.selectStation(Station_selectionnee);
                Sim.updateLine();
            }
            
        }
        
        /* -------------- Creation arete ------------- */
        
        if (Radio_arete.isSelected()){
            createLine(x, y);
        }
        /* -------------- Creation noeud ------------- */
        
        if (Radio_noeud.isSelected()){
            createNode(x, y);
        }
        
        fenetre_sim1.repaint();
    }//GEN-LAST:event_fenetre_sim1MousePressed

    private void Radio_deplacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_deplacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_deplacerActionPerformed
    
    private boolean cursorIsOnObject(int x, int y){
        if (Sim.getNodeFromPosition(x,y, 20, fenetre_sim1.img_station_size) != null){
            return true;
        }
        return false;
    }
    
    private void fenetre_sim1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fenetre_sim1MouseMoved
       
        jLabel2.setText("X:  "+evt.getX()+"  Y:  "+ evt.getY() );
        if (cursorIsOnObject(evt.getX(), evt.getY())){
            setCursor(fenetre_sim1.getHandCursor());
        } else{
            setCursor(fenetre_sim1.getDefaultCursor());
        }
        
    }//GEN-LAST:event_fenetre_sim1MouseMoved
    
    private void Bouton_supprimerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_supprimerMouseReleased

        
            
            
            if(Sim.deleteNode(selectedNode)){
                if(selectedNode.isStation){
                    Print.setText("Station supprimée avec succès.");
                }
                else{
                    Print.setText("Noeud supprimé avec succès.");
                }
            }
        
        if (selectedObjectType == "Circuit"){
            
            int i = liste_circuits.getSelectedIndex();
            if (i >= 0){


                int numero_circuit = selectedRoute.getNumber();
                Sim.deleteRoute(selectedRoute);
                defaultListModel.remove(i);
                selectedRoute = null;
                Print.setText("Circuit "+numero_circuit+ " supprimé avec succès.");


            }
            else{
            
                    Print.setText("Il n'y a rien de selectionné à supprimer.");
                

            }
        }
        fenetre_sim1.repaint();
    }//GEN-LAST:event_Bouton_supprimerMouseReleased

    private void Bouton_circuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_circuitActionPerformed
        // TODO add your handling code here:
        createRoute();
    }//GEN-LAST:event_Bouton_circuitActionPerformed

    private void ok_dialog_circuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_dialog_circuitActionPerformed
        // TODO add your handling code here:
        Dialog_circuit.dispose();
    }//GEN-LAST:event_ok_dialog_circuitActionPerformed

    private void Dialog_circuitWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Dialog_circuitWindowClosing
        // TODO add your handling code here:
        
        createRouteState ="reset";
        
    }//GEN-LAST:event_Dialog_circuitWindowClosing

    private void liste_circuitsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_liste_circuitsValueChanged
        // TODO add your handling code here:
        
       
            int i = liste_circuits.getSelectedIndex();
            if (i>=0){
                
                selectedRoute = Sim.getRouteFromIndex(i);
                selectedObjectType = "Circuit";
                Print.setText("Circuit sélectionné: "+selectedRoute.getNumber());
            }
            else{
                selectedRoute = null;
                selectedObjectType = "Circuit";
            }
        
    }//GEN-LAST:event_liste_circuitsValueChanged
    
    
    //nécéssaire quand il y a un seul circuit
    private void liste_circuitsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_liste_circuitsFocusGained
        // TODO add your handling code here:
        liste_circuitsValueChanged(null);
    }//GEN-LAST:event_liste_circuitsFocusGained


    private void Bouton_simulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_simulerActionPerformed
        if (!simTimer.running){
            
        simTimer.setSimSpeed(simulation_speed.getValue()/4);
        simTimer.start(Integer.parseInt(sim_duration.getText()), 16);
        fenetre_sim1.displayTimer.start();
                }

    }//GEN-LAST:event_Bouton_simulerActionPerformed

    private void Bouton_arreterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_arreterActionPerformed
        // TODO add your handling code here:
        
            simTimer.stop();
            fenetre_sim1.displayTimer.stop();
            fenetre_sim1.repaint();
         
    }//GEN-LAST:event_Bouton_arreterActionPerformed

    private void menuCommandAjouterStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCommandAjouterStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCommandAjouterStationActionPerformed

    private void sim_durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sim_durationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sim_durationActionPerformed

    private void simulation_speedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_simulation_speedStateChanged
        // TODO add your handling code here:
        simTimer.setSimSpeed(simulation_speed.getValue()/4);
    }//GEN-LAST:event_simulation_speedStateChanged

    private void Radio_areteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_areteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_areteActionPerformed

    private void Radio_noeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_noeudActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_Radio_noeudActionPerformed

    private void jInternalFrame1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInternalFrame1MouseEntered
        
    }//GEN-LAST:event_jInternalFrame1MouseEntered

    private void menuCommandAjouterNoeudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCommandAjouterNoeudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCommandAjouterNoeudActionPerformed

    private void menuOptionSeeCoordsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionSeeCoordsDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOptionSeeCoordsDisplayActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.print("Key pressed: "+evt.KEY_PRESSED);
        if (evt.KEY_PRESSED == 127){
            System.out.println("DELETE pressed");
        }
    }//GEN-LAST:event_formKeyPressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatHeure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatHeure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatHeure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatHeure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatHeure().setVisible(true);
           
            }
        });
    }
   
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_arreter;
    private javax.swing.JButton Bouton_circuit;
    private javax.swing.JButton Bouton_simuler;
    private javax.swing.JButton Bouton_supprimer;
    private javax.swing.JDialog Dialog_circuit;
    private javax.swing.JTextPane Print;
    private javax.swing.JRadioButton Radio_ajouter;
    private javax.swing.JRadioButton Radio_arete;
    private javax.swing.JRadioButton Radio_deplacer;
    private javax.swing.JRadioButton Radio_noeud;
    private javax.swing.JRadioButton Radio_select;
    private javax.swing.ButtonGroup buttonGroup1;
    private simulatheure.SimDisplay fenetre_sim1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList liste_circuits;
    private javax.swing.JMenuItem menuCommandAjouterCircuit;
    private javax.swing.JMenuItem menuCommandAjouterNoeud;
    private javax.swing.JMenuItem menuCommandAjouterStation;
    private javax.swing.JMenuItem menuCommandAnalResults;
    private javax.swing.JMenuItem menuCommandEnregSous;
    private javax.swing.JMenuItem menuCommandEnregistrer;
    private javax.swing.JMenuItem menuCommandLancerSim;
    private javax.swing.JMenuItem menuCommandModCircuit;
    private javax.swing.JMenuItem menuCommandNouvDoc;
    private javax.swing.JMenuItem menuCommandOuvrir;
    private javax.swing.JMenuItem menuCommandStopperSim;
    private javax.swing.JMenu menuFolderAffichage;
    private javax.swing.JMenu menuFolderCircuit;
    private javax.swing.JMenu menuFolderEdition;
    private javax.swing.JMenu menuFolderFichier;
    private javax.swing.JMenu menuFolderSimulation;
    private javax.swing.JCheckBoxMenuItem menuOptionSeeCircuitToolbox;
    private javax.swing.JCheckBoxMenuItem menuOptionSeeCoordsDisplay;
    private javax.swing.JCheckBoxMenuItem menuOptionSeeSimToolbox;
    private javax.swing.JCheckBoxMenuItem menuOptionSeeTooltipsDisplay;
    private javax.swing.JMenu menuSubfolderInformation;
    private javax.swing.JMenu menuSubfolderToolboxes;
    private javax.swing.JButton ok_dialog_circuit;
    private javax.swing.JTextField sim_duration;
    private javax.swing.JSlider simulation_speed;
    private javax.swing.JSpinner spin_freq;
    private javax.swing.JSpinner spin_num;
    private javax.swing.JSpinner spin_t;
    private javax.swing.JTextField text_nom;
    // End of variables declaration//GEN-END:variables
}
